In [3]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

url = 'https://goo.gl/bDdBiA'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(url, names=names)
array = dataframe.values
# separate array into input and output components
X = array[:,0:8]
y = array[:,8]
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(X)
# summarize transformed scale
set_printoptions(precision=3)
print(rescaledX[0:5,:])




[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


In [4]:
# Standardize data (0 mean, 1 stdev)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X)
X = scaler.transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(X[0:5,:])


[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


In [5]:
# Normalize data using Normalizer class
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(X)
X = scaler.transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(X[0:5,:])

[[ 0.294  0.389  0.069  0.416 -0.318  0.094  0.215  0.654]
 [-0.458 -0.609 -0.087  0.288 -0.376 -0.371 -0.198 -0.103]
 [ 0.409  0.644 -0.087 -0.427 -0.23  -0.366  0.2   -0.035]
 [-0.425 -0.502 -0.081  0.078  0.062 -0.249 -0.463 -0.524]
 [-0.187  0.083 -0.246  0.149  0.125  0.231  0.898 -0.003]]


In [ ]:
# Binarize data
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.0).fit(X)
X = binarizer.transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(X[0:5,:])
